{{/* https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack */}}
{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.additionalRules }}
{{- $prometheusAppName := include "dash.prom-name" . }}
{{- range $prometheusRuleName, $prometheusRule := .Values.prometheusOperator.additionalRules }}
{{- $prometheusRuleNameLength := len $prometheusRuleName }}
{{- $lengthToAbbreviate := sub 63 $prometheusRuleNameLength | int }}
{{- $abbreviatedPromAppName := $prometheusAppName | trunc $lengthToAbbreviate | trimSuffix "-" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" $abbreviatedPromAppName $prometheusRuleName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "dash.labels" $ | nindent 4 }}
    {{- if $prometheusRule.additionalLabels }}
    {{- toYaml $prometheusRule.additionalLabels | nindent 4 }}
    {{- end }}{{/* ends if $prometheusRule.additionalLabels */}}
    role: alert-rules
    app: {{ $abbreviatedPromAppName }}
spec:
  groups:
    {{- toYaml $prometheusRule.groups | nindent 4 }}

{{- end }}{{/* ends range */}}
{{- end }}{{/* ends and .Values.prometheusOperator.enabled .Values.prometheusOperator.additionalRules */}}
